import fitz  # PyMuPDF
import io
from datetime import datetime
from typing import Dict, Any

class PDFGeneratorService:
    def generate_audit_report(self, proposal_data: Dict[str, Any]) -> bytes:
        """
        Generates a professional engineering audit report in PDF format.
        """
        doc = fitz.open()
        page = doc.new_page()
        
        # Colors & Fonts
        header_color = (0.91, 0.44, 0.13) # Accent orange
        
        # Header
        page.insert_text((50, 50), "ENGINEERING AUDIT REPORT", fontname="helv", fontsize=18, color=header_color)
        page.insert_text((50, 70), f"Generated by Digital Geotech Hub AI", fontname="helv", fontsize=10, color=(0.5, 0.5, 0.5))
        
        # Object Info
        y = 100
        page.insert_text((50, y), "1. PROJECT SPECIFICATION", fontname="helv", fontsize=12)
        y += 20
        
        parsed = proposal_data.get("parsed_data", {})
        info_lines = [
            f"Work Type: {parsed.get('work_type', 'N/A')}",
            f"Volume: {parsed.get('volume', 'N/A')} t/m",
            f"Depth: {parsed.get('depth', 'N/A')} m",
            f"Soil Type: {parsed.get('soil_type', 'N/A')}",
            f"Required Profile: {parsed.get('required_profile', 'N/A')}"
        ]
        
        for line in info_lines:
            page.insert_text((70, y), str(line), fontname="helv", fontsize=10)
            y += 15
            
        # Technical Summary
        y += 20
        page.insert_text((50, y), "2. TECHNICAL SUMMARY", fontname="helv", fontsize=12)
        y += 20
        summary = proposal_data.get("technical_summary", "No summary provided")
        page.insert_textbox(fitz.Rect(70, y, 540, y + 200), summary[:1000], fontname="helv", fontsize=10)
        y += 220
        
        # Footer
        page.insert_text((50, 780), "Digital Geotech Hub | geotech-hub.ru", fontname="helv", fontsize=8, color=(0.7, 0.7, 0.7))
        
        pdf_bytes = doc.write()
        doc.close()
        return pdf_bytes

pdf_generator = PDFGeneratorService()
